FROM public.ecr.aws/lambda/python:3.7

COPY c1ws-py-sdk/ .

RUN python3 -m pip install .

# Copy function code
COPY lambda.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda.lambda_handler" ]